### ISSUE TITLE
camera intrinsic matrix

### ISSUE THREAD

**Issue by Luckyalum** [jby1993/BCNet#15]
Thank you for your code.
As mentioned in the paper, all training data share a common camera intrinsic matrix. Can you provide the intrinsic matrix of the camera? I want to use projection to generate multi-view images. 
Thank you.

**Comment by jby1993** [comment]
https://github.com/jby1993/BCNet/blob/master/code/module/ImageReconstructModel.py#L511

**Comment by Luckyalum** [comment]
Thank You!
