### ISSUE TITLE
About Garment PCA

### ISSUE THREAD

**Issue by Luckyalum** [jby1993/BCNet#16]
我在进行一些实验的时候发现 alpha(衣物的 PCA)随机取一些值会得到不太合理的结果，就像图里所示。
我在论文里没有找到关于Garment PCA的生成过程（类似于SMPL的统计学习过程），请问PCA基是怎么获得的呢，或者如何得到一个比较符合真实情况的alpha呢（比较光滑，不会出现渗透等等）？
![image](https://user-images.githubusercontent.com/17925314/144196282-d806532c-3e44-4cd3-91ef-a2ee6759b998.png)

**Comment by jby1993** [comment]
将合成的中性姿态下的同一类衣物转换为连接一致的网格后，对这些数据进行PCA即可得到平均形状和基形状。你可以用sklearn里的PCA代码来处理。出现严重扭曲应该是基的系数给的不对造成的，可能是太大了

**Comment by Luckyalum** [comment]
谢谢回复，确实和基系数有关，我尝试加上关于基系数的先验和光滑loss，得到了很好的的效果。
