### ISSUE TITLE
About the evaluation on BCNet

### ISSUE THREAD

**Issue by mirror58229** [jby1993/BCNet#18]
Thanks for sharing your work! It helps me a lot!
I have a question that how we can compare the BCNet with other work,  which mentioned in 5.2, " Because our model predicts separate body and garment meshes, we extract the outer surface of all meshes as the proxy to do registration and error computing for a fair comparison. " 

I don't know how to extract the outer surface of the result of BCNet, could you show the code or the method?

Thank you very much!

**Comment by jby1993** [comment]
There is a method to do this. You can render the original mesh to multi-views and extract the visible surface points and normals, then use Poisson reconstruction to reconstruct the whole surface point clouds. By this method, you should get a watertight surface mesh.

**Comment by mirror58229** [comment]
OK I got it! Thanks for your reply!
