### ISSUE TITLE
about torch_geometric install, the problem and the solution that I meet.

### ISSUE THREAD

**Issue by SMY19999** [jby1993/BCNet#22]
python 3.8
torch 1.10.2 cu113

`
conda install pyg -c pyg
`
i got 
torch-cluster 1.6.0
torch-scatter 2.0.9
torch-sparse 0.6.13
torch-spline-conv 1.2.1
torch-geometric 2.0.4

follow the author
`
pip install torch_geometric==1.5.0
`
when i run the infer.py, 
The error like:
cannot import name 'container_abcs' from 'torch._six'

follow the [blog](https://blog.csdn.net/weixin_45628042/article/details/129963098):

go to the python3.8/site-packages/torch_geometric/data/data/dataloader.py line5 

change
`
from torch._six import container_abs,string_classes,int_classes
`
to
`
import collections.abc as container_abcs
int_classes = int
string_classes = str
`
Finally, I run infer.py successfully.

**Comment by shash29-dev** [comment]
This is really helpful
