### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for ImageReconstructModel:

### ISSUE THREAD

**Issue by trilokpadhi** [jby1993/BCNet#4]
Hi @jby1993 
Thanks for the awesome work and making the code public .
I tried running the model for python3.7 and pytorch1.6 , but still I am getting this issue .
Can you please help me resoslve this ?

Thanks
Trilok

`Traceback (most recent call last):
  File "infer.py", line 116, in <module>
    net.load_state_dict(torch.load('../models/garNet.pth',map_location='cpu'),True)
  File "/home/trilok/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ImageReconstructModel:
	Missing key(s) in state_dict: "skinWsNet.ress.0.conv1.att_l", "skinWsNet.ress.0.conv1.att_r", "skinWsNet.ress.0.conv1.lin_l.weight", "skinWsNet.ress.0.conv1.lin_r.weight", "skinWsNet.ress.0.conv2.att_l", "skinWsNet.ress.0.conv2.att_r", "skinWsNet.ress.0.conv2.lin_l.weight", "skinWsNet.ress.0.conv2.lin_r.weight", "skinWsNet.ress.1.conv1.att_l", "skinWsNet.ress.1.conv1.att_r", "skinWsNet.ress.1.conv1.lin_l.weight", "skinWsNet.ress.1.conv1.lin_r.weight", "skinWsNet.ress.1.conv2.att_l", "skinWsNet.ress.1.conv2.att_r", "skinWsNet.ress.1.conv2.lin_l.weight", "skinWsNet.ress.1.conv2.lin_r.weight", "skinWsNet.ress.2.conv1.att_l", "skinWsNet.ress.2.conv1.att_r", "skinWsNet.ress.2.conv1.lin_l.weight", "skinWsNet.ress.2.conv1.lin_r.weight", "skinWsNet.ress.2.conv2.att_l", "skinWsNet.ress.2.conv2.att_r", "skinWsNet.ress.2.conv2.lin_l.weight", "skinWsNet.ress.2.conv2.lin_r.weight", "skinWsNet.ress.3.conv1.att_l", "skinWsNet.ress.3.conv1.att_r", "skinWsNet.ress.3.conv1.lin_l.weight", "skinWsNet.ress.3.conv1.lin_r.weight", "skinWsNet.ress.3.conv2.att_l", "skinWsNet.ress.3.conv2.att_r", "skinWsNet.ress.3.conv2.lin_l.weight", "skinWsNet.ress.3.conv2.lin_r.weight". 
	Unexpected key(s) in state_dict: "skinWsNet.ress.0.conv1.lin.weight", "skinWsNet.ress.0.conv1.att_i", "skinWsNet.ress.0.conv1.att_j", "skinWsNet.ress.0.conv2.lin.weight", "skinWsNet.ress.0.conv2.att_i", "skinWsNet.ress.0.conv2.att_j", "skinWsNet.ress.1.conv1.lin.weight", "skinWsNet.ress.1.conv1.att_i", "skinWsNet.ress.1.conv1.att_j", "skinWsNet.ress.1.conv2.lin.weight", "skinWsNet.ress.1.conv2.att_i", "skinWsNet.ress.1.conv2.att_j", "skinWsNet.ress.2.conv1.lin.weight", "skinWsNet.ress.2.conv1.att_i", "skinWsNet.ress.2.conv1.att_j", "skinWsNet.ress.2.conv2.lin.weight", "skinWsNet.ress.2.conv2.att_i", "skinWsNet.ress.2.conv2.att_j", "skinWsNet.ress.3.conv1.lin.weight", "skinWsNet.ress.3.conv1.att_i", "skinWsNet.ress.3.conv1.att_j", "skinWsNet.ress.3.conv2.lin.weight", "skinWsNet.ress.3.conv2.att_i", "skinWsNet.ress.3.conv2.att_j".`

**Comment by jby1993** [comment]
Hi @trilokpadhi 
This error is caused by [GATConv incompatible of the pytorch_geometric](https://github.com/rusty1s/pytorch_geometric/issues/1755). I have convert my model to compatible with torch_geometric 1.5.0. Maybe you need to check your version.
