### ISSUE TITLE
Comparison with Existing Methods

### ISSUE THREAD

**Issue by zhangyahu1** [jby1993/BCNet#5]
Thanks for sharing your work!

I have two questions in your Table 2:  1) why not test all methods on BUFF and DW dataset? 2) The corner mark 3 said 'We did not test [38, 7] on this dataset as most of the samples are not A-pose.' However, DW dataset is from MGN.

**Comment by jby1993** [comment]
The default setting of MGN and Octopus require a rough A pose input, we have emailed the author about this. The DW is the dataset from MGN, but it is not A pose.

**Comment by zhangyahu1** [comment]
Thanks for your reply. What about testing all methods on BUFF dataset?

**Comment by jby1993** [comment]
You mean PIFu on BUFF? Their Chamfer is very good. I forgot the number or you can check the value in their paper. On our test setting, we is a little better on garment values, but their chamfer should be better.

**Comment by zhangyahu1** [comment]
Thanks!
